---
title: "Fed's Forward Guidance"
subtitle: "*Some Stylised Facts and recent performance*"
date: "04/22/2023"
draft: false
categories:
  - Monetary Policy
  - Inflation  
execute:
   echo: false
format: 
  html: default
  pdf: default
#format:
#  html:
#    code-fold: true
#   pdf: default
title-block-banner: false
comments:
  hypothesis: 
    theme: clean
---

<div align="justify">

> -   *Over the past two years, the Federal Reserve has been criticized by a wide range of actors, including the International Monetary Fund (IMF), financial markets, top academic economists, and even its own top officials, for being too slow to act on inflation and maintaining a monetary policy stance that is too loose given record high inflation. However, many of these arguments still rely on backward-looking measures, such as the distance of the policy rate from neutral, as well as on "old-school" thinking that implicitly ignores how much of an impact forward guidance can have.*

> -   *In this post, I present a few key facts about how the Federal Reserve has used forward guidance in recent decades. I also discuss how the Fed's credibility has added a record-high degree of extra tightening, which began much sooner than is publicly discussed or acknowledged.*

## Introduction

In the world of central banking, there are few policies that have been as widely discussed in recent years as forward guidance and balance sheet changes. These policy tools, known as non-conventional policies, define the broader monetary policy stance that goes beyond just setting the policy rate. For example, forward guidance is a method used by central banks to directly communicate or signal their intentions in order to shape expectations and influence interest rates in the desired direction. During the 2008 financial crisis, forward guidance and Quantitative Easing (QE) became especially critical tools, as the policy rate hit zero. In order to continue stimulating the economy, the Federal Reserve (Fed) needed to find new ways to do so. As Ben [Bernanke](https://www.amazon.co.uk/21st-Century-Monetary-Policy-Inflation/dp/1324020466/ref=sr_1_1?adgrpid=1172080352962224&hvadid=73255235197595&hvbmt=be&hvdev=c&hvlocphy=4923&hvnetw=o&hvqmt=e&hvtargid=kwd-73255197392577%3Aloc-188&hydadcr=18495_2211395&keywords=21st+century+monetary+policy&qid=1681764141&sr=8-1) put it, "*we had to be creative*." Forward guidance allowed the Fed to do just that. More recently, forward guidance has played an important role in the ongoing debate over inflation. In this post, I will be looking at a few stylized facts about how the Fed uses this tool.

## Measuring Unconventional Policies

One way to measure the Fed's unconventional policies is to look at the "proxy rate", which is published by the Federal Reserve Bank of San Francisco (See [here](https://www.frbsf.org/economic-research/indicators-data/proxy-funds-rate/) and [here](https://www.frbsf.org/economic-research/publications/economic-letter/2022/november/monetary-policy-stance-is-tighter-than-federal-funds-rate/)). The proxy rate combines the Fed's policy rate with the level of interest rate implied by the balance sheet changes and direct communication. Hence it incorporates the hypothetical interest rate that associates with the unconventional components of monetary policy.

```{python}

import pandas as pd
import os
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import zscore, iqr
import seaborn as sns
import statsmodels.api as sm

matplotlib.rcParams.update({'font.size': 8})
plt.style.use('seaborn')


def add_year_decade_dummies(df):
    df['Year'] = df.index.year
    df['Decade'] = [int(np.floor(year / 10) * 10) for year in np.array(df["Year"])]
    return df

```

```{python}
# download data from: https://www.frbsf.org/economic-research/indicators-data/proxy-funds-rate/

folder = '/Users/safishajjouz/Google Drive/1. Thesis/inflation_papers/Data'
file_name = 'proxy-funds-rate-data.xlsx'
file_to_load = os.path.join(folder, file_name)

# load data
data = pd.read_excel(file_to_load, skiprows=9)
data['Date'] = data['Date'].dt.tz_localize(None)
data = data.set_index('Date')
data.columns = ['Fed_rate', 'Proxy_rate']
data['Forward_Guidance'] = data['Proxy_rate'] - data['Fed_rate']

```

I have plotted the proxy and policy rate in @fig-1 below. The proxy rate leads the actual policy rate because of the way monetary policy is implemented. Typically, the markets are set up in anticipation of a change in the policy rate before the change actually takes place. This pattern is (unsurprisingly) pronounced after 2007.

Before the global financial crisis, the proxy rate and the fund rate were closely correlated. However, they started to diverge after 2007, when quantitative easing (QE) and forward guidance became integral components of the monetary policy framework. During this period, the use of forward guidance amounted to a monetary policy stance of negative interest rates (validating the purpose that it was designed). These ultra-low interest rates persisted until 2014 according to the proxy rate. At that point the Fed started tightening its policy until the pandemic hit.

```{python}
#| label: fig-1
#| fig-cap: "The Proxy and Policy Rate"

fig, axes = plt.subplots(1, 2, gridspec_kw={"hspace": 0.5}, figsize=(10, 4))
plot1 = data[['Proxy_rate', 'Fed_rate']].plot(ax=axes[0], title='The Fed and Forward Guidance', legend=False,  ylabel='Interest rate(%)')
plot1.set(xlabel=None)
plot2 = data[['Proxy_rate', 'Fed_rate']][data.index >= '2006-01-01'].plot(ax=axes[1],
                                                                          title='The Fed and Forward Guidance Post-GFC')
plt.legend(['Proxy Rate', 'Fund rate'])
plot2.set(xlabel=None)
plt.show()

```

<p>

</p>

The Fed has been criticized (including by respected [academics](https://www.lse.ac.uk/CFM/assets/pdf/CFM-Discussion-Papers-2022/CFMDP2022-09-Paper.pdf)) for acting too slowly to address inflation, but the truth is that they began to tighten financial conditions well before the interest rate hikes. In fact, they started eight months before the first hike in March 2022, and almost a year and a half after the pandemic shock (@fig-1). This is important to note, because when the Fed changed course, inflation was mostly driven by [supply-side factors](https://www.frbsf.org/economic-research/indicators-data/supply-and-demand-driven-pce-inflation/), such as supply chain disruptions and labor shortages. This left less room for monetary policy to do much. However, the Fed clearly began to change course before the pressure from the demand side on inflation started to substantially pick up.

It's worth emphasizing that even prior to the Global Financial Crisis (GFC), the proxy rate and the fund rate were not identical. Part of this discrepancy can be attributed to the inevitable measurement errors involved in calculating a statistical measure such as the proxy rate. Of course, it's impossible to completely eliminate statistical errors, but we can reasonably assume that most of the difference between the proxy rate and the fund rate can be attributed to communication-related factors.

This evidence makes it clear that the inclusion of forward guidance and other unconventional tools has expanded the criteria by which the monetary policy stance should be evaluated. It is now clear that the Fed has become looser than it appears when stimulating the economy, and tighter than the policy rate indicates when tightening. As a result, it is becoming more important to get a better sense of the magnitude of the non-conventional aspects of monetary policy. The following paragraphs will examine this issue more closely.

## "Until the Job is Done"

The difference between the proxy and policy rate shows the level of interest rate implied by the Fed's forward guidance. @fig-2 shows exactly this. For example, at the peak of the proxy rate during this monetary policy tightening cycle, the Fed added an extra 3% to the policy rate by just pointing what will be doing. This means that until October 2022, the economy was effectively operating at an interest rate level closer to 6% than the official policy rate of 3%[^1]. It was only after October 2022 that the proxy rate start coming off, signaling a less hawkish stance.

[^1]: It is sometimes surprising to hear Fed officials (such as James B. Bullard) support their arguments for the appropriate policy rate by referring to the Taylor rule, without considering the effects of direct communication, including the signals that their analysis sends to the markets. But it is even more surprising that analysts, journalists, and strategists often perpetuate the flaws in their thinking.

```{python}
int_range = iqr(data['Forward_Guidance'], rng=(25, 75))
```

```{python}
#| label: fig-2
#| fig-cap: Interest Rates equivalent of Direct Communication

plt3 = data[['Forward_Guidance']].plot(color='teal', title='Forward Guidance (Interest Rate Equivalent)', legend=False)
plt3.axhline(y=int_range, color='blue', linewidth=0.5, linestyle="--")
plt3.axhline(y=0, color='black', linewidth=1, linestyle="--")
plt3.axhline(y=int_range * -1, color='blue', linewidth=0.5, linestyle="--", label='Interquartile Range')
plt.show()
```

<p>

</p>

Fed's tone shift was mostly evident in Jay Powell's Jackson Hole speech last August who declared \`\`the Federal Reserve must keep at it until the job is done". The US stock market slid sharply after Powell spoke, with the benchmark S&P 500 index falling 3.4 per cent, while the tech-heavy Nasdaq Composite tumbled 3.9 per cent, recording the one biggest one-day decline for both indices (outside sudden crashes).

To put things in perspective, in @fig-3 I show the magnitude of this and other messages since 2020 and compare the unconventional part of the monetary policy to historical standards. The calculations are still based on the distance between the proxy rate and the policy rate. The left panel shows the average impact of communication-related factors across all tightening episodes since mid-70s as identified by the proxy rate. For the relevant periods, I have also filtered out the direct impact of balance sheet changes[^2]. The right panel shows the distribution of the interest rates implied by forward guidance across each decades[^3].

[^2]: To filter out the direct impact of balance sheet changes, I controlled for the change in 10Y Treasuries. This may not completely capture the full impact, but it should be close. Only the first round of QE was strong enough. Subsequent rounds were less effective as markets anticipated the Fed's actions. That is the reason why Bernanke wanted more QE to offset these effects and compensate for the tight fiscal policy at the time. A classic study is the one by [Krishnamurthy and Vissing-Jorgensen](https://www.nber.org/papers/w17555).

[^3]: For readers not familiar with box plots see this [post](https://en.wikipedia.org/wiki/Box_plot)

```{python}

full_data = pd.read_csv('/Users/safishajjouz/Google Drive/1. Thesis/inflation_papers/Data/full_data.csv')
leg_names = ["Total Impact of Unconventional Policies", "Communication and Other Signalling Channels", 'Impact of Sheet Balance Changes']
temp_df_box_plot = full_data[['Forward_Guidance', 'Decade']].copy()
temp_df_box_plot['Decades'] = [str(x) + "'s" for x in temp_df_box_plot['Decade']]


means_tc_adjusted_proxy_rate = full_data[
    ['Proxy_rate', 'Fed_rate', 'Forward_Guidance', 'i_fq', 'i_qe', 'tc_adjusted_proxy_rate']].groupby(
    by=['tc_adjusted_proxy_rate']).mean()
means_tc_adjusted_proxy_rate = means_tc_adjusted_proxy_rate.reset_index().drop([0])
means_tc_adjusted_proxy_rate = means_tc_adjusted_proxy_rate.set_index('tc_adjusted_proxy_rate')


means_tc_adjusted_proxy_rate.index = [
    '1976-12 - 1980-03',
    '1980-07 -1981-09',
    '1983-02 -1984-08',
    '1988-03 - 1989-04',
    '1993-10 - 1995-02',
    '1998-10 - 2000-06',
    '2003-07 - 2006-07',
    '2014-09 - 2018-12',
    '2021-05 - 2023-02']

```

```{python}

#| label: fig-3
#| fig-cap: Monetary Policy Tightening Cycles

fig, axes = plt.subplots(1, 2, gridspec_kw={"hspace": 0.5}, figsize=(10, 4))
bar_plot = means_tc_adjusted_proxy_rate[['Forward_Guidance', 'i_fq', 'i_qe']].plot.bar(ax=axes[0], stacked=False,
                                                                                       rot=80,
                                                                                       title="Non-Conventional Policies Across Tightening Cycles")
bar_plot.title.set_size(8)
bar_plot.tick_params(labelsize=7)
bar_plot.set(ylabel='Interest rate (%)')
bar_plot.legend(leg_names, frameon=False, prop={'size': 8})

box_plot = sns.boxplot(ax=axes[1], x='Decades', y='Forward_Guidance',
                       data=temp_df_box_plot[['Forward_Guidance', 'Decades']])
box_plot.set_title('Distribution of Signalling Channel (Forward Guidance)')
box_plot.title.set_size(8)
box_plot.set(ylabel='Distribution of Interest rates (%)')
box_plot.set(xlabel=None)
plt.show()
```

<p>

</p>

Ben Bernanke once said that "monetary policy is 99% words and 1% action." This was certainly true in the current tightening cycle, where the Fed's words had an unprecedented impact. The Fed's communication and signaling factors added (on average) an additional 1.5 percent of interest rates hikes, which is three times more than the most aggressive Fed of the past.

The credibility factor also played a role here. Before gaining the "credibility medal" the Fed struggled to convince the markets in the first two tightening cycles in Figure 3, even though it raised rates significantly. Things changed with Paul Volcker, but it wasn't until forward guidance became part of the monetary policy transmission mechanism that markets started taking the Fed seriously.

Another way to look at the impact of the Fed's messaging in recent years is to look at the right panel of @fig-3, where I have plotted the distribution of the impact of forward guidance (in terms of interest rates). The Fed is now more likely to be seen as hawkish than dovish, given its seriousness in fighting inflation and the fact that markets still have faith in its words. This was not the case in the 1970s and 1980s. It is also worth noting that the formal incorporation of forward guidance has managed to have a relatively even impact across different economic conditions, indicating some ability to weigh the balance of risks and fine-tune its words to the situation.

## The implications for Soft Landing

In the meantime, the Fed has carried out the swiftest policy rate increase in the history of the United States. As I have briefly discussed in a previous [post](https://msh855.github.io/TheQuantEconomist/posts/fed_and_private_consumption/the_fed_and_private_consumption.html), the present interest rate level suggests that the impact on output is likely to be just as significant. This implies that the response from the Fed's end has been sufficiently forceful in all areas under its *direct* control. It's hard not to draw the conclusion that we are presently experiencing the most hawkish monetary policy position in recent US history, and its repercussions are just beginning to materialize[^4].

[^4]: We can discuss about the level of interest rates, but as I have explained in an earlier [post](https://msh855.github.io/TheQuantEconomist/posts/fed_and_private_consumption/the_fed_and_private_consumption.html) I am very critical of the standard practice in using the distance of the policy rate relative to the neutral rates to indicate how neutral monetary policy is.

Does this mean that a [soft landing](https://www.investopedia.com/terms/s/softlanding.asp) is off the table? That's a whole other discussion. But the short answer is "No". In fact, the opposite is true. According to this evidence, the Fed's actions are what kept a soft landing on the cards. And, this shouldn't be surprising. Technically, only the Fed needs to comply to a soft landing because of its mandate to balance maximum employment and price stability. Other central banks don't have this restriction[^5].

[^5]: Although, they still care about unemployment to avoid overshooting or undershooting inflation.

Nevertheless, soft landing is still the holy grail of central banking. [R. Dornbusch](https://en.wikipedia.org/wiki/Rudi_Dornbusch) famously said, "*No postwar recovery has died in bed of old age---the Federal Reserve has murdered every one of them*". The most notable (and technically the only) soft landing in the most recent 16 business cycles occurred in 1994 under Alan Greenspan. Inflation was rising rapidly in 1994, and Greenspan raised interest rates seven times in the space of a year, bringing them up to 6%. This was a significant increase, but it did not cause a recession. In fact, the economy continued to grow throughout 1994 and 1995. Why was it successful? Economists will pick three main reasons:

-   First, the economy was strong at the time, which helped to cushion the impact of the higher interest rates.
-   Second, Greenspan was able to communicate his intentions clearly to the public, which helped to reduce uncertainty.
-   Third, Greenspan was able to raise interest rates gradually, giving businesses and consumers time to adjust.

In @fig-5, I plotted this episode and compared it to the current tightening cycle. I also added the "Hard landing" of Volcker (which was essentially started by Burns and Miller) and the in-between tightening cycle of 1999 to make the case clearer. Before the 1980s, any comparisons are meaningless, as the Gold Standard was in place, there was a substantially different monetary policy framework, and fiscal dominance was the norm. I also ignored the tightening cycle that preceded the Global Financial Crisis (for obvious reasons) and the tightening cycle of 2018, as it was disrupted by the pandemic.

```{python}
#| label: fig-5
#| fig-cap: Monetary Policy Tightening Cycles
fig, axes = plt.subplots(2, 2, gridspec_kw={"hspace": 0.5}, figsize=(10, 4))
plt1 = data[['Proxy_rate', 'Fed_rate']][(data.index >= '1976-01-01') & (data.index <= '1985-01-01')].plot(ax=axes[0, 0],
                                                                                                          legend=False,
                                                                                                          rot=30,
                                                                                                          ylabel='Interest rate(%)',
                                                                                                          fontsize=7)
plt1.set_title("Burns-Miller-Volcker's Hard Landing(s)", fontsize=7)

plt1.set(xlabel=None)
plt1.tick_params(axis='x', which='both', labelsize=8)
plt1.tick_params(axis='y', which='both', labelsize=8)

plt2 = data[['Proxy_rate', 'Fed_rate']][(data.index >= '1993-01-01') & (data.index <= '1998-01-01')].plot(ax=axes[0, 1],
                                                                                                          rot=35,
                                                                                                          legend=False)
plt2.set_title("Greenspan's Soft Landing", fontsize=7)
plt2.set(xlabel=None)
plt2.tick_params(axis='x', which='both', labelsize=8)
plt2.tick_params(axis='y', which='both', labelsize=8)

plt3 = data[['Proxy_rate', 'Fed_rate']][(data.index >= '2021-01-01') & (data.index <= '2024-01-01')].plot(ax=axes[1, 1],
                                                                                                          rot=35)
plt3.legend(['Proxy Rate', 'Fund rate'])
plt3.set_title("Current Tightening Cycle", fontsize=7)
plt3.set(xlabel=None)
plt3.tick_params(axis='x', which='both', labelsize=8)
plt3.tick_params(axis='y', which='both', labelsize=8)

plt4 = data[['Proxy_rate', 'Fed_rate']][(data.index >= '1998-01-01') & (data.index <= '2001-01-01')].plot(ax=axes[1, 0],
                                                                                                          rot=35,
                                                                                                          legend=False)

plt4.set_title("Fed's January 1999–July 2000 Tightening Cycle", fontsize=7)
plt4.set(xlabel=None)
plt4.tick_params(axis='x', which='both', labelsize=8)
plt4.tick_params(axis='y', which='both', labelsize=8)
plt.show()
```

<p>

</p>

The Fed's reaction function under Greenspan and now is quite similar, including making up for Friedman's "long and variable lags." However, unlike in the past, the use of unconventional tools allows the Fed to adjust its policy more smoothly and early on, without raising the policy rate. The three conditions that made Greenspan a legend continue to hold in some reasonable sense. The dynamics are also similar to the tightening cycle of 1999, which ended with the dot-com crash. However, as the "mini" banking crisis clearly demonstrated, the financial system is much more resilient today. Of course, there are some factors that are different between now and then, such as the starting level of inflation. 

To conclude, a soft landing is primarily a fine-tuning exercise that is difficult to achieve, almost identical if not as elusive as timing the market. Based on the evidence here, the Fed has taken all necessary steps to achieve this goal and some of the necessary conditions for a soft landing are clearly met. But I do think that, overall, luck factors are more important than they were in the past[^6]. 

[^6]: I call "luck factors" the factors that central banks cannot fully control, such as consumer and business behavior. These behaviors are generally stable and predictable, but they can be disrupted by indirect or second-round effects of monetary policy. These indirect effects are what make the effects of monetary policy have "long and variable lags." Supply shocks are also "luck factors" as are any other unanticipated shocks. In addition, a soft landing substantially depends on the pace at which central banks want to bring inflation down. A fast pace implies less chance of a soft landing, as it would require the real economy to be crashed. Too slow also reduces the chance of a soft landing, as there is a high chance that inflation expectations will become de-anchored and new unfavorable shocks will hit the system.
