project:
  type: website
  output-dir: docs

website:
  title: "Moustafa Chatzouz"
  site-url: https://www.the-quant-economist.com #https://msh855.github.io/TheQuantEconomist
  description: "Observations about Macroecnomics, Finance and Public Debates"
  page-footer:
    left: "Usual Disclaimer applies"

  navbar:
    #right:
     # - text: Home
     #   href: home.qmd
    right:
      #- text: Macroeconomics for Social Change
      #  href: macro_for_social_change.qmd
      - text: About
        href: about.qmd
      - text: Housing Calculation Dashboard
        href: housing_cal_dashboard.qmd
      #- text: Academic Research
      #  href: academic_research.qmd
      - icon: github
        href: https://github.com/msh855
      #- icon: twitter
       # href: https://twitter.com/Hajjouz
      - icon: linkedin
        href: https://www.linkedin.com/in/moustafa-chatzouz/
     # - icon: rss
      #  href: index.xml

  google-analytics:  "170377145"
  cookie-consent: false
# # filters:
#  - code-filename

execute:
  freeze: auto

#format:
#  html:
#    theme: yeti
#    css: styles.css

resources:
  - CNAME

format:
  html:
    theme:
      light: theme.scss #yeti
      dark: Darkly
## ref: https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html

