project:
  type: website
  output-dir: docs

website:
  title: "Moustafa Chatzouz"
  #subtitle: "Bringing clarity to the world of finance"
  site-url: https://msh855.github.io/TheQuantEconomist
  description: "Observations about Macroecnomics, Finance and Public Debates"
  page-footer:
    left: "Usual Disclaimer applies"
  listing:
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    feed: true
  title-block-banner: true

  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Home
        href: home.qmd
      - icon: github
        href: https://github.com/msh855
      - icon: twitter
        href: https://twitter.com/Hajjouz
      - icon: linkedin
        href: https://www.linkedin.com/in/moustafa-chatzouz/
    #  - icon: rss
    #    href: index.xml

  google-analytics:  "170377145"
  cookie-consent: false
  filters:
  - code-filename

execute:
  freeze: auto

format:
  html:
    theme: yeti
    css: styles.css
