project:
  type: website
  output-dir: docs

website:
  title: "Moustafa Chatzouz"
  site-url: https://msh855.github.io/TheQuantEconomist #https://www.the-quant-economist.com
  description: "Observations about Macroecnomics, Finance and Public Debates"
  page-footer:
    left: "Usual Disclaimer applies"
#  listing:
#    contents: posts
#    sort: "date desc"
#    type: default
#    categories: true
#    feed: true
#  title-block-banner: true

  navbar:
    #right:
     # - text: Home
     #   href: home.qmd
    right:
      #- text: Macroeconomics for Social Change
      #  href: macro_for_social_change.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/msh855
      - icon: twitter
        href: https://twitter.com/Hajjouz
      - icon: linkedin
        href: https://www.linkedin.com/in/moustafa-chatzouz/


    #  - icon: rss
    #    href: index.xml

  google-analytics:  "170377145"
  cookie-consent: false
# # filters:
#  - code-filename

execute:
  freeze: auto

#format:
#  html:
#    theme: yeti
#    css: styles.css

format:
  html:
    theme:
      light: theme.scss #yeti
      dark: Darkly
## ref: https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html

