project:
  type: website
  output-dir: docs

website:
  title: "The Quant Economist Blog"
  site-url: https://www.the-quant-economist.com #https://msh855.github.io/TheQuantEconomist
  description: "Observations about Macroecnomics, Finance and Public Debates"
  page-footer:
    left: "Usual Disclaimer applies"

  navbar:
    #right:
     # - text: Home
     #   href: home.qmd
    left: 
     - text: ChatGPT Economics
       href: chatGPT_blog.qmd
       
    right:
      - text: About
        href: about.qmd
     
      
      - icon: github
        href: https://github.com/msh855
      - icon: linkedin
        href: https://www.linkedin.com/in/moustafa-chatzouz/
      - icon: rss
        href: index.xml

  google-analytics:  "170377145"
  cookie-consent: false
# # filters:
#  - code-filename

execute:
  freeze: auto

#format:
#  html:
#    theme: yeti
#    css: styles.css

resources:
  - CNAME

format:
  html:
    theme:
      light: theme.scss #yeti
      dark: Darkly
## ref: https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html

