---
# title: "Academic Research"
format: html
editor: visual
draft: true 
---

<div align="justify"> 

## Academic Background and Research  

I started my PhD in fiscal policy in 2010, at the height of the Greek sovereign debt crisis. At the time, there was a lot of debate about whether Greece's debt adjustment program would be successful in reducing its debt-to-GDP ratio.

One way to assess this possibility is to estimate the so-called fiscal multipliers, which measure the impact of a change in government spending or tax revenues on output. This was a good way to start my PhD research, as a common problem for PhD students is finding a research question to work on.

The value of the fiscal multipliers determines whether debt-to-GDP can go up or down with fiscal consolidations. For example, if a cut in spending has a more than proportional impact on output, then the debt-to-GDP ratio can increase. This is because the numerator (debt) falls slower than the denominator (GDP).

The value of the fiscal multipliers also determines whether fiscal consolidations should be spending- or tax-driven. If spending multipliers are higher than tax multipliers, then it is better to have fiscal consolidations that are tax-driven, as this will have less of an impact on the economy.

The literature on fiscal multipliers is vast, both theoretically and empirically. However, there was little to no empirical research on fiscal multipliers in Greece at the time I started my PhD. For the record, my research confirmed that the standard textbook assumptions about fiscal multipliers might be correct for Greece. This contradicted the assumption made by the IMF at the time (such "miscalculation" made headlines later).


After I did some initial research, I moved on to more complex topics. There are some deep and unanswered questions in economics that do not have easy answers. The low interest rate environment and the calls for fiscal policy to play a more active role after the financial crisis have revived old debates and classic discussions about public debt.

<!--
While there are clearly bad cases for using public debt, there are also good reasons to do so. The most important reason is that capitalism is inherently flawed due to two factors: uncertainty and the finite ability of people to work.

Capitalism can fail for many reasons in practice, but most of those reasons can be fixed in theory. For example, if monopolies and rent-seeking are to blame, societies and governments can find ways to remove those distortions. However, it is much harder to account for the inherent inability of humanity to predict the future or have people live forever. According to neoclassical theory, these two factors are sufficient to cause the private sector to misallocate resources. These are the fundamental causes of market failures, which means that capitalism will never allocate resources as efficiently as Adam Smith envisioned. Instead, it will tend to over-accumulate capital (excesses). This is not a new idea; Marx predicted the same thing. However, it is also the central proposition of neoclassical economics. Unfortunately, you may not have heard about it because it is often ignored by academics and journalists, who are more interested in ideology than in understanding the real world. To understand why, who can absorb the excess savings other than the government ?  

The most obvious example of this is the low interest rate environment that began in the early 1980s. The primary cause of this was the death of a large number of people. China's one-child policy and the lack of a strong social safety net also contributed to this problem.
--> 

[to be completed ....]



