---
title: "UK's Autumn 2022 Budget: A Comment"
subtitle: "UK's budget is a bet that inflation is transitory and is designed in keeping Tories in power"
date: "11/18/2022"
author: "Moustafa Chatzouz"
format: html
categories:
  - Fiscal Policy
editor: visual
---

<div align="justify">

> -   *UK's budget is a bet that inflation is transitory and is designed in keeping Tories in power*.

## The Sunak-Hunt Budget

Budget Day today, besides my congratulations to my ex-colleagues for making the hard work in the background, a few quick reactions.

Today's Budget was an off the shelf, "Play it Safe" Sunak's Budget: nothing too negative, nothing too positive. Balance the political and economic risks in the short-run, reduce debt - mostly after the planned elections in two years - and make sure it meets OBR's forecasts on paper (i.e. its forecasts) than in reality.

Minimal to nothing to support long-term growth, that is potential output, which has a deflationary impact over time and hence helps people to have cheaper mortgages. To be fair, no political party has a serious structural reform agenda.

Also, the distributional implications will be subject to debate. According to OBR, in just two years, inflation wiped out 8 years of real wage growth for most households in the UK. After the budget, most of the vulnerable will still see real wages falling.

The overall fiscal stance is mostly tuned to the expected peak in inflation, pushing back the actual austerity after the elections. In general, how to tackle inflation through fiscal policy is not easy, but blind austerity is also not the answer (I will try to come back with a more detailed post in due time). Key point is that fiscal policy is much more likely to have a much higher impact on output than reduce inflation via aggregate demand. Letting BoE lead in the fight over inflation and doing the minimum by not adding fuel to the fire makes some sense. The Budget delivers such ideas.

Hunt also mentioned that inflation is mostly driven by global factors. Although this is correct, I think this rather exposes the Government than can be used as an excuse. The Labor party never seized the opportunity to attack this statement by pointing out that price caps is a good defence against global shocks. The Americans after all did it quite successfully in response to the post-war commodity price pressures and the Spanish Flu.  


Why is price caps an optimal response to rising inflation due to global factors? Besides the obvious protection to households, energy price caps are equivalent to closing the borders to the widespread global virus.  Price caps effectively a) convert a supply side problem to a demand problem and b) increase the relative importance of domestic to global factors. Together this implies that the national governments and central banks can have a greater control over inflation and thus contribute to a less uncertain outlook.

Price caps came quite late and with no clear plan on what is next beyond that seem to be conditioned on market expectations. Remember that when governments in the past had to manage similar inflation problems, inflation jumped once the price caps were lifted. Keeping inflation in a durable, and more importantly a more certain falling path, required price caps to be imposed much sooner with a much more clear plan, ideally linked to the overall risks in the global and domestic economy than accept the wishful thinking in the markets.
